### ISSUE TITLE
Thorium Checklist

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/beryllium#30]
* [x] MessageBox
* [x] version
* [x] init
* [x] token
* [x] create_window
* [x] num_joysticks
* [x] game_controller_open
* [x] game_controller_num_mappings
* [x] add_mapping
* [x] mapping_for_device_index
* [x] game_controller_event_state
* [x] set_game_controller_event_state
* [x] game_controller_mapping_for_guid
* [x] game_controller_name_for_index
* [x] Window
* [x] create_renderer
* [x] size
* [x] set_size
* [x] display_mode
* [x] set_display_mode
* [x] set_screen_style
* [x] Renderer
* [x] clear
* [x] create_texture_from_surface
* [x] copy
* [x] present
* [x] Texture
* [x] GameControllerEventState
* [x] RumbleNotSupported
* [x] AddMappingError
* [x] GameController
* [x] name
* [x] product
* [x] product_version
* [x] vendor
* [x] attatched
* [x] mapping
* [x] bind_for_axis
* [x] axis
* [x] button
* [x] set_rumble
* [x] player_index
* [x] joystick_id
* [x] ControllerBindButton
* [x] ControllerButton
* [x] ControllerAxis
* [x] WindowEvent
* [x] AudioDeviceID
* [x] open_audio_device
* [x] queue_audio
* [x] clear_queued_audio
* [x] pause_device
* [x] DLL Loading
* [x] Function Loading
* [x] Surfaces
* [x] Events

**Comment by Lokathor** [comment]
Much of the controller stuff is now a distinct checklist: https://github.com/Lokathor/beryllium/issues/34
