### ISSUE TITLE
Surface tracker

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/beryllium#42]
* [ ] Surface uses NonNull
* [ ] SDL_BlitScaled
* [ ] SDL_BlitSurface
* [ ] SDL_ConvertPixels
* [ ] SDL_ConvertSurface
* [ ] SDL_ConvertSurfaceFormat
* [ ] ~~SDL_CreateRGBSurface~~
* [ ] ~~SDL_CreateRGBSurfaceFrom~~
* [ ] ~~SDL_CreateRGBSurfaceWithFormat~~
* [ ] ~~SDL_CreateRGBSurfaceWithFormatFrom~~
* [ ] SDL_FillRect
* [ ] SDL_FillRects
* [x] SDL_FreeSurface
* [x] SDL_GetClipRect
* [ ] SDL_GetColorKey
* [ ] SDL_GetSurfaceAlphaMod
* [ ] SDL_GetSurfaceBlendMode
* [ ] SDL_GetSurfaceColorMod
* [ ] SDL_LoadBMP
* [ ] SDL_LoadBMP_RW
* [x] SDL_LockSurface
* [ ] SDL_LowerBlit
* [ ] SDL_LowerBlitScaled
* [ ] SDL_MUSTLOCK
* [ ] SDL_SaveBMP
* [ ] SDL_SaveBMP_RW
* [x] SDL_SetClipRect
* [ ] SDL_SetColorKey
* [ ] SDL_SetSurfaceAlphaMod
* [ ] SDL_SetSurfaceBlendMode
* [ ] SDL_SetSurfaceColorMod
* [x] SDL_SetSurfacePalette
* [ ] SDL_SetSurfaceRLE
* [x] SDL_UnlockSurface

**Comment by Lokathor** [comment]
this consumes https://github.com/Lokathor/beryllium/issues/22

**Comment by Lokathor** [comment]
Surface creation is tracked by https://github.com/Lokathor/beryllium/issues/59, so we'll strike out the boxes here
