### ISSUE TITLE
SDL_pixels.h

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/beryllium#48]
Enumerations

* [x] SDL_PixelFormatEnum
* [x] SDL_PIXELTYPE
* [x] SDL_PIXELORDER
* [x] SDL_PIXELLAYOUT
* [x] SDL_BITSPERPIXEL
* [x] SDL_BYTESPERPIXEL
* [x] SDL_ISPIXELFORMAT_INDEXED
* [x] SDL_ISPIXELFORMAT_ALPHA
* [x] SDL_ISPIXELFORMAT_FOURCC

Structures

* [x] SDL_Color
* [x] SDL_Palette
* [x] SDL_PixelFormat

Functions

* [x] SDL_AllocFormat
* [x] SDL_AllocPalette
* [ ] SDL_CalculateGammaRamp
* [x] SDL_FreeFormat
* [x] SDL_FreePalette
* [x] SDL_GetPixelFormatName
* [x] SDL_GetRGB
* [x] SDL_GetRGBA
* [x] SDL_MapRGB
* [x] SDL_MapRGBA
* [x] SDL_MasksToPixelFormatEnum
* [x] SDL_PixelFormatEnumToMasks
* [x] SDL_SetPaletteColors
* [x] SDL_SetPixelFormatPalette

**Comment by Lokathor** [comment]
https://github.com/Lokathor/beryllium/issues/43 is its own thing
