### ISSUE TITLE
Renderer tracker

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/beryllium#50]
* [ ] Renderer in its own file
* [ ] Renderer uses NonNull
* [ ] Texture in its own file
* [ ] Texture uses NonNull

Enumerations

* [ ] SDL_BlendFactor
* [ ] SDL_BlendOperation
* [x] SDL_RendererFlags
* [ ] SDL_RendererFlip
* [ ] SDL_TextureAccess
* [ ] SDL_TextureModulate

Structures

* [x] SDL_Renderer
* [ ] SDL_RendererInfo
* [x] SDL_Texture

Functions

* [ ] SDL_ComposeCustomBlendMode
* [x] SDL_CreateRenderer
* [ ] SDL_CreateSoftwareRenderer
* [ ] SDL_CreateTexture
* [x] SDL_CreateTextureFromSurface
* [ ] SDL_CreateWindowAndRenderer
* [x] SDL_DestroyRenderer
* [x] SDL_DestroyTexture
* [ ] SDL_GL_BindTexture
* [ ] SDL_GL_UnbindTexture
* [ ] SDL_GetNumRenderDrivers
* [ ] SDL_GetRenderDrawBlendMode
* [x] SDL_GetRenderDrawColor
* [ ] SDL_GetRenderDriverInfo
* [ ] SDL_GetRenderTarget
* [ ] SDL_GetRenderer
* [ ] SDL_GetRendererInfo
* [x] SDL_GetRendererOutputSize
* [ ] SDL_GetTextureAlphaMod
* [ ] SDL_GetTextureBlendMode
* [ ] SDL_GetTextureColorMod
* [ ] SDL_LockTexture
* [ ] SDL_QueryTexture
* [x] SDL_RenderClear
* [x] SDL_RenderCopy
* [ ] SDL_RenderCopyEx
* [x] SDL_RenderDrawLine
* [x] SDL_RenderDrawLines
* [ ] SDL_RenderDrawPoint
* [ ] SDL_RenderDrawPoints
* [ ] SDL_RenderDrawRect
* [ ] SDL_RenderDrawRects
* [ ] SDL_RenderFillRect
* [ ] SDL_RenderFillRects
* [ ] SDL_RenderGetClipRect
* [ ] SDL_RenderGetIntegerScale
* [ ] SDL_RenderGetLogicalSize
* [ ] SDL_RenderGetScale
* [ ] SDL_RenderGetViewport
* [ ] SDL_RenderIsClipEnabled
* [x] SDL_RenderPresent
* [ ] SDL_RenderReadPixels
* [ ] SDL_RenderSetClipRect
* [ ] SDL_RenderSetIntegerScale
* [ ] SDL_RenderSetLogicalSize
* [ ] SDL_RenderSetScale
* [ ] SDL_RenderSetViewport
* [ ] SDL_RenderTargetSupported
* [ ] SDL_SetRenderDrawBlendMode
* [x] SDL_SetRenderDrawColor
* [ ] SDL_SetRenderTarget
* [ ] SDL_SetTextureAlphaMod
* [ ] SDL_SetTextureBlendMode
* [ ] SDL_SetTextureColorMod
* [ ] SDL_UnlockTexture
* [ ] SDL_UpdateTexture
* [ ] SDL_UpdateYUVTexture
