### ISSUE TITLE
Surface creation fixup

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/beryllium#59]
* [ ] [SDL_CreateRGBSurface](https://wiki.libsdl.org/SDL_CreateRGBSurface) is currently used, but with a fake "Surface Format" type that we should delete (Closes #31)
* [ ] [SDL_CreateRGBSurfaceFrom](https://wiki.libsdl.org/SDL_CreateRGBSurfaceFrom) basically uses a `&mut P` as the pixel data for the Surface to manipulate.
* [ ] [SDL_CreateRGBSurfaceWithFormat](https://wiki.libsdl.org/SDL_CreateRGBSurfaceWithFormat) is, I think, the easiest to call version because you pass the fewest args and then it figures the rest out.
* [ ] [SDL_CreateRGBSurfaceWithFormatFrom](https://wiki.libsdl.org/SDL_CreateRGBSurfaceWithFormatFrom) Combines the above two things: pass a PixelFormatEnum value and _also_ use a `&mut P`
